### ISSUE TITLE
Xen API changes in xenctrl

### ISSUE THREAD

**Issue by Wenzel** [Wenzel/libmicrovmi#20]
Xen breaks the API between `4.9.2` and `4.11.2`

4.9.2: `xc_monitor_enable(domid_t domid)`
4.11.2: `xc_monitor_enable(uint32_t domid)`

How to deal with this in Bindgen ?

**Comment by rageagainsthepc** [comment]
I don't know whether I understand your question, but wouldn't it be valid for both APIs if you just wrote `xc_domain_maximum_gpfn(xc, domid.try_into().unwrap(), &mut max_gpfn as _);` instead of assigning the domid to a `u16` variable beforehand?
https://github.com/Wenzel/xenctrl/blob/0e1177d231b721f23ce6e19e6117543109e3fbcd/src/lib.rs#L81

**Comment by rageagainsthepc** [comment]
Oh yeah, I think I get it now, sorry. But at least you could compile it for your specific xenctrl version without errors ;)

**Comment by Wenzel** [comment]
Closing this issue, as your PR has been merged.
